tenya_pro/about_myself/urls.py
from django.urls import path

from . import views

app_name = 'about_myself'
urlpatterns = [
    path('', views.index, name='about_myself'),

]

tenya_pro/blog/urls.py
from django.urls import path

from .views import BlogPostView, BlogDetailView

app_name = 'blog'
urlpatterns = [
    path('', BlogPostView.as_view(), name='blog_base'),
    path('<int:pk>/', BlogDetailView.as_view(), name='det_base'),


]

tenya_pro/main/urls.py
from django.urls import path

from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

tenya_pro/portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.det_gallery, name='det_gallery'),

]

tenya_pro/service/urls.py
from django.urls import path

from . import views

app_name = 'service'
urlpatterns = [
    path('', views.index, name='index'),

]

tenya_pro/tenya_pro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'), name='blog'),
    path('about_myself/', include('about_myself.urls'), name='about_myself'),
    path('portfolio/', include('portfolio.urls'), name='portfolio'),
    path('service/', include('service.urls'), name='service'),
    path('', include('main.urls'), name='main')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenya_pro/about_myself/models.py
from django.db import models


class Myself(models.Model):
    about_myself_text = models.TextField('text')

    def __str__(self):
        return self.about_myself_text

tenya_pro/blog/models.py
from django.db import models


class Blog(models.Model):
    blog_title = models.CharField('blog title', max_length=200)
    blog_text = models.TextField('blog text')
    blog_pub_date = models.DateTimeField('public date')
    blog_image = models.ImageField('blog image', upload_to='../media/blog/')

    def __str__(self):
        return self.blog_title

tenya_pro/portfolio/models.py
from django.db import models


class Portfolio(models.Model):
    port_title = models.CharField('port title', max_length=200)
    port_text = models.TextField('port text')
    port_pub_date = models.DateTimeField('public date')
    port_image = models.ImageField('port image', upload_to='../media/')

    def __str__(self):
        return self.port_text


class PostsImages(models.Model):
    port_images = models.ImageField(upload_to='../media/', blank=True)
    post = models.ForeignKey(Portfolio, related_name='PostsImages', on_delete=models.CASCADE)

tenya_pro/service/models.py
from django.db import models

# Create your models here.

tenya_pro/about_myself/views.py
from django.shortcuts import render

from .models import Myself


def index(request):
    text = Myself.objects.get(id=1)
    return render(request, 'about_myself/about_myself.html', {'text': text})

tenya_pro/blog/views.py
from .models import Blog
from django.views.generic import ListView, DetailView


class BlogPostView(ListView):
    model = Blog
    template_name = 'blog/blog_base.html'


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/det_base.html'

tenya_pro/main/views.py
from django.shortcuts import render

from portfolio.models import Portfolio, PostsImages


def index(request):
    port_list = Portfolio.objects.all()
    return render(request, 'main/first.html', {'port_list': port_list})

tenya_pro/portfolio/views.py
from django.shortcuts import render
from .models import Portfolio, PostsImages


def index(request):
    port_list = Portfolio.objects.all()
    return render(request, 'portfolio/first.html', {'port_list': port_list})


def det_gallery(request, article_id):
    port_list_det = Portfolio.objects.get_queryset().filter(id=article_id)
    port_list_det_all = PostsImages.objects.get_queryset().filter(post_id=article_id)
    return render(request, 'portfolio/det_gallery_first.html', {'det_gallery': port_list_det,
                                                                'list_all': port_list_det_all})

tenya_pro/service/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'service/service.html')

tenya_pro/about_myself/templates/about_myself/about_myself.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About myself</title>
    <link rel="stylesheet" href="{% static '.\about_myself\css\reset.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '.\about_myself\css\about_myself.css' %}" type="text/css">
<style>

</style>

</head>
<body>

    <header class="header">
        <div class="container">
            <div class="header__top">
                <nav class="menu">
                    <ul class="menu__list">
                        <li class="menu__list-item">
                            <a class="menu__list-link" href="../">Main</a>
                        </li>
                        <li class="menu__list-item">
                            <a class="menu__list-link" href="/service/">Services</a>
                        </li>
                        <li class="menu__list-item">
                            <a class="menu__list-link" href="../portfolio/">Portfolio</a>
                        </li>
                        <li class="menu__list-item">
                            <a class="menu__list-link" href="../blog/">Blog</a>
                        </li>
                        <li class="menu__list-item">
                            <a class="menu__list-link" href="../about_myself/">Contacts</a>
                        </li>
                    </ul>
                </nav>
                <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
            </div>
        </div>
    </header>

    </div>
        <img class="main_image" src="{% static '.\about_myself\media\photo1.jpg' %}" alt="photo">
    </div>

    <section class="advice page-section" >
        <div class="container">
            <div class="advice__inner">
                <div class="advice__form">
                    <div class="advice__title">
                        CONTACT
                        <span>me</span>
                    </div>
                    <form class="advice__form" >
                        <div class="advice__form--title"></div>
                        <input class="advice__form-name" type="text" placeholder="Name">
                        <input class="advice__form-phone" type="text" placeholder="Phone">
                        <button class="advice__form__btn" type="submit">SEND</button>
                    </form>
                </div>
                <img class="advice__image" src="{% static '.\main\media\background_main.jpg' %}" alt="">
            </div>
        </div>
    </section>

    <footer class="footer">
        <div class="footer__items">
            <div class="footer__item">
                <p>Telephone number:</p>
                <a href="tel:+380501753343">+38(050)175-33-43</a>
            </div>
            <div class="footer__item">
                <p>Mail:</p>
                <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
            </div>
            <div class="footer__item">
                <p>Socials:</p>
                <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
                <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
            </div>
        </div>
        <p class="footer__end">MY DESIGN © All rights reserved</p>
    </footer>


</body>
</html>

tenya_pro/blog/templates/blog/blog.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>BLOG</title>
    <link rel="stylesheet" href="{% static '.\blog\css\reset.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '.\blog\css\blog.css' %}" type="text/css">
<style>

</style>
</head>
<body>

  <header class="header">
    <div class="container">
        <div class="header__top">
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../">Main</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/service/">Services</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/portfolio/">Portfolio</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/blog/">Blog</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/about_myself/">Contacts</a>
                    </li>
                </ul>
            </nav>
            <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
        </div>
    </div>
  </header>


  <section class="blog page-section">
    <div class="container">
      <h3 class="blog__title">
        BLOG
              <span>latest news about everything</span>
      </h3>
        <div class="row">
        <div class="leftcolumn">
        {% block content%}{% endblock %}
        </div>
        <div class="rightcolumn">
        </div>
  </div>


    </div>
  </section>




  <footer class="footer">
        <div class="footer__items">
            <div class="footer__item">
                <p>Telephone number:</p>
                <a href="tel:+380501753343">+38(050)175-33-43</a>
            </div>
            <div class="footer__item">
                <p>Mail:</p>
                <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
            </div>
            <div class="footer__item">
                <p>Socials:</p>
                <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
                <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
            </div>
        </div>
      <p class="footer__end">MY DESIGN © All rights reserved</p>
    </footer>

</body>
</html>

tenya_pro/blog/templates/blog/blog_base.html
{% extends "./blog.html" %}

{% block content%}

        {% for i in blog_list %}
<div class="leftcolumn">
    <div class="card">
      <a href="{% url 'blog:det_base' i.id %}">{{i.blog_title}}</a>
      <h5>{{i.blog_pub_date}}</h5>
      <img src="{{i.blog_image.url}}" height="300">
    </div>
</div>
        {% endfor %}

{% endblock %}

tenya_pro/blog/templates/blog/det_base.html
{% extends "./detail.html" %}

{% block content %}
    <h3 class="blog__title">{{blog.blog_title}}</h3>
    <img src="{{blog.blog_image.url}}" height="600">
    <p>{{blog.blog_text}}</p>
{% endblock %}

tenya_pro/blog/templates/blog/detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>BLOG</title>
    <link rel="stylesheet" href="{% static '.\blog\css\reset.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '.\blog\css\blog.css' %}" type="text/css">
<style>

</style>
</head>
<body>

    <header class="header">
    <div class="container">
        <div class="header__top">
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/">Main</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/service/">Services</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/portfolio/">Portfolio</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/blog/">Blog</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/about_myself/">Contacts</a>
                    </li>
                </ul>
            </nav>
            <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
        </div>
    </div>
  </header>

    <section class="blog page-section">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </section>
  <footer class="footer">
        <div class="footer__items">
            <div class="footer__item">
                <p>Telephone number:</p>
                <a href="tel:+380501753343">+38(050)175-33-43</a>
            </div>
            <div class="footer__item">
                <p>Mail:</p>
                <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
            </div>
            <div class="footer__item">
                <p>Socials:</p>
                <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
                <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
            </div>
        </div>
      <p class="footer__end">MY DESIGN © All rights reserved</p>
    </footer>

</body>
</html>

tenya_pro/main/templates/main/first.html
{% extends "./main.html" %}

{% block content%}


<div class="portfolio__gallery">
      <div class="portfolio__items">
          {% for i in port_list %}
          <div class="portfolio__item animation">
                  <a href="{% url 'portfolio:det_gallery' i.id %}"><img src="{{i.port_image.url}}" height=300 alt=""></a>
                  <a class="portfolio__text" href="{% url 'portfolio:det_gallery' i.id %}">{{i.port_title}}</a>
          </div>
          {% endfor %}
          </div>
      </div>
</div>


{% endblock %}

tenya_pro/main/templates/main/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>MAIN</title>
    <link rel="stylesheet" href="{% static '.\main\css\reset.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '.\main\css\fotorama.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '.\main\css\main.css' %}" type="text/css">

</head>
<body>
    <header class="header">
    <div class="container">
        <div class="header__top">
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../">Main</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/service/">Services</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../portfolio/">Portfolio</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../blog/">Blog</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../about_myself/">Contacts</a>
                    </li>
                </ul>
            </nav>
            <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
        </div>
        <h1 class="header__title">
            Khrystyna Prokopenko
            <span>interior design</span>
        </h1>
    </div>
    </header>

    <section class="service">
        <h3 class="service__title title">
              SERVICES
              <span>what we can do</span>
        </h3>
        <div class="service__content">
            <div class="service__gallery">
                <div class="fotorama"
                    data-width="800"
                    data-height="550"
                    data-transition="crossfade"
                    data-loop="true"
                    data-autoplay="3000">
                    <img src="{% static '.\main\media\photo1.jpg' %}" alt="">
                    <img src="{% static '.\main\media\photo2.jpg' %}" alt="">
                    <img src="{% static '.\main\media\photo3.jpg' %}" alt="">
                </div>
            </div>
            <div class="service__text">
                <p>INTERIOR DESIGN We create spaces in which it is pleasant and comfortable to be.
                  Our experts understand how important a unique and atmospheric modern interior design is.
                  We carry out design projects of any complexity.</p>
            </div>
        </div>
    </section>

    <section class="portfolio page-section">
    <div class="container">
      <h3 class="portfolio__title">
        PORTFOLIO
              <span>my proud works</span>
      </h3>
    </div>
          {% block content%} {% endblock %}
    </section>

    <section class="advice page-section" >
        <div class="container">
            <div class="advice__inner">
                <div class="advice__form">
                    <div class="advice__title">
                        CONTACT
                        <span>me</span>
                    </div>
                    <form class="advice__form" >
                        <div class="advice__form--title"></div>
                        <input class="advice__form-name" type="text" placeholder="Name">
                        <input class="advice__form-phone" type="text" placeholder="Phone">
                        <button class="advice__form__btn" type="submit">SEND</button>
                    </form>
                </div>
                <img class="advice__image" src="{% static '.\main\media\background_main.jpg' %}" alt="">
            </div>
        </div>
    </section>

    <footer class="footer">
        <div class="footer__items">
            <div class="footer__item">
                <p>Telephone number:</p>
                <a href="tel:+380501753343">+38(050)175-33-43</a>
            </div>
            <div class="footer__item">
                <p>Mail:</p>
                <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
            </div>
            <div class="footer__item">
                <p>Socials:</p>
                <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
                <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
            </div>
        </div>
        <p class="footer__end">MY DESIGN © All rights reserved</p>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static '.\main\js\fotorama.js' %}"></script>

</body>
</html>

tenya_pro/portfolio/templates/portfolio/det_gallery.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>PORTFOLIO</title>
    <link rel="stylesheet" href="{% static '.\portfolio\css\reset.css' %}" type="text/css">
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '.\portfolio\css\det_gallery.css' %}" type="text/css">


</head>

<body>
  <header class="header">
    <div class="container">
        <div class="header__top">
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../../">Main</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/service/">Services</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/portfolio/">Portfolio</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/blog/">Blog</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/about_myself/">Contacts</a>
                    </li>
                </ul>
            </nav>
            <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
        </div>
    </div>
  </header>

  <section class="portfolio page-section">
    {% block content%} {% endblock %}
  </section>


  <footer class="footer">
      <div class="footer__items">
          <div class="footer__item">
              <p>Telephone number:</p>
              <a href="tel:+380501753343">+38(050)175-33-43</a>
          </div>
          <div class="footer__item">
              <p>Mail:</p>
              <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
          </div>
          <div class="footer__item">
              <p>Socials:</p>
              <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
              <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
          </div>
      </div>
      <p class="footer__end">MY DESIGN © All rights reserved</p>
  </footer>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="{% static '.\portfolio\js\fotorama.js' %}"></script>

</body>
</html>

tenya_pro/portfolio/templates/portfolio/det_gallery_first.html
{% extends "./det_gallery.html" %}

{% block content %}

<div class="portfolio__gallery">
       {% for j in det_gallery %}
        <p>{{j.port_title}}</p>
        <p>{{j.port_text}}</p>
        {% endfor %}
        <div class="fotorama"
            data-width="800"
            data-height="650"
            data-transition="crossfade"
            data-loop="true"
            data-autoplay="3000"
            data-allowfullscreen="true">
            {% for j in det_gallery %}
            <img src="{{j.port_image.url}}">
            {% endfor %}
            {% for i in list_all %}
            <img src="{{i.port_images.url}}">
            {% endfor %}
        </div>
</div>

{% endblock %}

tenya_pro/portfolio/templates/portfolio/first.html
{% extends "./portfolio.html" %}

{% block content%}

        {% for i in port_list %}

<div class="portfolio__gallery">
      <div class="portfolio__items">
          <div class="portfolio__item animation">
              <a href="{% url 'portfolio:det_gallery' i.id %}"><img src="{{i.port_image.url}}" height=300 alt=""></a>
              <a class="portfolio__text" href="{% url 'portfolio:det_gallery' i.id %}">{{i.port_title}}</a>
          </div>
      </div>
</div>
        {% endfor %}

{% endblock %}

tenya_pro/portfolio/templates/portfolio/portfolio.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>PORTFOLIO</title>
    <link rel="stylesheet" href="{% static '.\portfolio\css\reset.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '.\portfolio\css\portfolio.css' %}" type="text/css">

</head>
<body>
  <header class="header">
    <div class="container">
        <div class="header__top">
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../">Main</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/service/">Services</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../portfolio/">Portfolio</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../blog/">Blog</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../about_myself/">Contacts</a>
                    </li>
                </ul>
            </nav>
            <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
        </div>
    </div>
  </header>

  <section class="portfolio page-section">
    <div class="container">
      <h3 class="portfolio__title">
        PORTFOLIO
              <span>my proud works</span>
      </h3>
    </div>
    <div class="portfolio__gallery">
      <div class="portfolio__items">
          {% block content%} {% endblock %}
      </div>
    </div>
  </section>

  <footer class="footer">
      <div class="footer__items">
          <div class="footer__item">
              <p>Telephone number:</p>
              <a href="tel:+380501753343">+38(050)175-33-43</a>
          </div>
          <div class="footer__item">
              <p>Mail:</p>
              <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
          </div>
          <div class="footer__item">
              <p>Socials:</p>
              <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
              <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
          </div>
      </div>
      <p class="footer__end">MY DESIGN © All rights reserved</p>
  </footer>

</body>
</html>

tenya_pro/service/templates/service/service.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
    <title>PORTFOLIO</title>
    <link rel="stylesheet" href="{% static '.\service\css\reset.css' %}" type="text/css">
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '.\service\css\service.css' %}" type="text/css">
</head>

<body>
    <header class="header">
    <div class="container">
        <div class="header__top">
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="../../">Main</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/service/">Services</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/portfolio/">Portfolio</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/blog/">Blog</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" href="/about_myself/">Contacts</a>
                    </li>
                </ul>
            </nav>
            <a class="header__phone" href="tel:+380501753343">+38(050)175-33-43</a>
        </div>
    </div>
  </header>

    <section class="service">
        <h3 class="service__title">
              SERVICES
              <span>what we can do</span>
        </h3>
        <div class="service__content">
            <div class="service__gallery">
                <div class="fotorama"
                    data-width="800"
                    data-height="550"
                    data-transition="crossfade"
                    data-loop="true"
                    data-autoplay="3000">
                    <img src="{% static '.\service\media\photo1.jpg' %}" alt="">
                    <img src="{% static '.\service\media\photo2.jpg' %}" alt="">
                    <img src="{% static '.\service\media\photo3.jpg' %}" alt="">
                </div>
            </div>
            <div class="service__text">
                <p>INTERIOR DESIGN We create spaces in which it is pleasant and comfortable to be.
                  Our experts understand how important a unique and atmospheric modern interior design is.
                  We carry out design projects of any complexity.</p>
            </div>
        </div>
    </section>


    <footer class="footer">
      <div class="footer__items">
          <div class="footer__item">
              <p>Telephone number:</p>
              <a href="tel:+380501753343">+38(050)175-33-43</a>
          </div>
          <div class="footer__item">
              <p>Mail:</p>
              <a href="mailto:tenyapro@gmail.com">tenyapro@gmail.com</a>
          </div>
          <div class="footer__item">
              <p>Socials:</p>
              <a href="https://www.facebook.com/chilipizzadesign" target="_blank">Facebook</a>
              <a href="https://www.instagram.com/khrystyna_prokopenko/" target="_blank">Instagram</a>
          </div>
      </div>
      <p class="footer__end">MY DESIGN © All rights reserved</p>
  </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static '.\service\js\fotorama.js' %}"></script>
</body>
</html>